name: 'Get new data'
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download data
        uses: wei/wget@v1.1.1
        with:
          args: -O miesta.html "https://korona.kosice.sk/spolocna-zodpovednost/"
      - name: Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          add: 'miesta.html'
          message: 'New data from https://korona.kosice.sk/spolocna-zodpovednost/'
          pull_strategy: '--rebase'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}